project:
  type: website
  output-dir: docs

website:
  title: "parkinsons-microbial-blood-signatures"
  site-url: https://jboktor.github.io/parkinsons-microbial-blood-signatures
  
  navbar:
    # logo: images/SarkisMazmanianLabLogo.png
    href: https://sarkis.caltech.edu/
    right: 
      # - href: notebooks/00_index.qmd
      - text: "About"
        href: notebooks/00_about.qmd
      - text: "Background"
        href: notebooks/00_background.qmd
      - text: "Results"
        href: notebooks/00_results.qmd
      - text: "Notes"
        href: notebooks/00_notes.qmd
      - icon: github
        href: https://github.com/jboktor/parkinsons-microbial-blood-signatures

format:
  html:
    theme: [sandstone, custom.scss]
    css: styles.css
    toc: true
    toc-title: Contents
    toc-location: left

editor: visual
