project:
  type: website
  output-dir: docs

website:
  title: "parkinsons-blood-signatures"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: [sandstone, custom.scss]
    css: styles.css
    toc: true
    toc-title: Contents
    toc-location: left

editor: visual

