project:
  type: website
  output-dir: docs

website:
  title: "parkinsons-blood-signatures"
  navbar:
    logo: images/SarkisMazmanianLabLogo.png
    href: https://sarkis.caltech.edu/
    right: 
      # - href: index.qmd
      #   text: Home
      - text: "About"
      - href: notebooks/_about.qmd
      - text: "Background"
      - href: notebooks/_background.qmd
      - text: "Results"
      - href: notebooks/_results.qmd
      - text: "Notes"
      - href: notebooks/_notes.qmd
      - icon: github
        href: https://github.com/jboktor/parkinsons-microbial-blood-signatures

format:
  html:
    theme: [sandstone, custom.scss]
    css: styles.css
    toc: true
    toc-title: Contents
    toc-location: left

editor: visual

