---
title: "Adaptive Immune Receptor Repertoire in Parkinson's Disease: Optimal Transport and Probabilistic Modeling Approaches for Latent Space Embeddings"
editor: visual
author: "Joe Boktor"
date: '2023-12-07'
bibliography: references.bib
format: 
  html:
    font-family: helvetica neue
    page-layout: full
    toc: true
    toc-location: left
    toc-depth: 4
    self-contained: true
    code-fold: true
    code-tools: true
    fig-align: center
    grid:
      sidebar-width: 300px
      body-width: 900px
      margin-width: 300px
      gutter-width: 1.5rem
---

```{r setup, include=FALSE}
#| warning: false
#| message: false

library(tidyverse)
library(janitor)
library(styler)  
library(glue)
library(listenv)
library(furrr)
library(tictoc)
library(progress)
library(data.table)
library(fastICA)
library(parallelDist)
library(mclust)
library(seqinr)
library(progress)
library(transport)
# dimensionality reduction
library(umap)
# plotting
library(ggsci)
library(plotly)
library(aplot)
library(patchwork)

home_dir <- "/central/groups/MazmanianLab/joeB"
pdmbs_dir <- paste0(home_dir, "/PDMBS")
ref_dir <- paste0(home_dir, "/Downloads/RefDBs")
wkdir <- paste0(pdmbs_dir, "/parkinsons-microbial-blood-signatures")
src_dir <- paste0(wkdir, "/notebooks")
source(paste0(src_dir, "/R_scripts/_load-core-pkgs.R"))
source(paste0(src_dir, "/R_scripts/_misc_functions.R"))
source(paste0(src_dir, "/R_scripts/_airr-modeling_funcs.R"))
load_dot_env(glue("{wkdir}/.env"))
scratch_dir <- "/central/scratch/jbok/PDMBS"
t4_bucket = Sys.getenv('GCS_TRUST4')
```


```{mermaid}
graph TD
    A(Inputs)
    A1(anthraquinone \nprecursors)
    A2(battery \nmembranes)
    A3(battery \ncontainers)
    B(Processes & \nBattery Chemistry)
    C(Battery Architecture \nIntegration)
    D(Integration with \n KWh scale facilities)
    E(Customer: \n5G Base Stations)

    A1 --> A
    A2 --> A
    A3 --> A
    A -->|Processing| B
    B -->|Integration| C
    C -->|Deployment| D
    D -->|Delivery| E

```

```{r}
#| fig-width: 9
#| fig-height: 9

# dimred <- readRDS(
#     glue("{wkdir}/figures/AIRR/PCA_ProsT5-viztest.rds")
# )

# dimred$pca_C

```


```{r}
#| fig-width: 9
#| fig-height: 9

# dimred$pca_mixtures

```


```{r}
#| fig-height: 9
#| fig-width: 9

# dimred$pca_grouping
```


